### ISSUE TITLE
Trying to regenerate nanogenmo article results

### ISSUE THREAD

**Issue by smokeyblues** [tra38/ZombieWriter#6]
Hi Tariq. My dad found [this](https://dev.to/tra/using-machine-learning-to-generate-human-readable-news-articles) article you wrote and asked me if I can teach him how to use ZombieWriter. I tried to recreate similar articles using nanogenmo.csv and the ruby script you had in the article. I am currently trying again right now on an EC2 GPU instance and it has been at 100% CPU for the last 20 minutes so I think it is hanging. 

Can you help me figure out what I am missing? 

Here are [my notes](https://gist.github.com/smokeyblues/85864d69ffdf0bb399b33a09c75a714f) if that helps. I'm writing them for my dad. 

Thanks in advance!

Aaron

**Comment by tra38** [comment]
Hey @smokeyblues,

If you need to speed up the processing power of the Ruby script, you should have [GNU GSL](http://www.gnu.org/software/gsl) and [rb-gsl](https://rubygems.org/gems/rb-gsl) (a Ruby gem that interfaces with the GSL library) also installed on the machine as well. According to classifier-reborn's documentation, GSL will speed up LSI by 10x, and to be honest, that's what I used for the demonstration as well. (Not using GSL means that we are using the default implementation of LSI in classifier-reborn and that default implementation is pretty slow and buggy.)

Someone else recently had a [similar problem with running ZombieWriter without GSL](https://github.com/tra38/ZombieWriter/issues/5)...and was able to finally get ZombieWriter to work by running these commands on a Ubuntu machine...

```
sudo apt install linuxbrew-wrapper
brew install gsl
sudo apt-get install libgsl0-dev
gem install gsl
```

Run them before running the Ruby script, and I think you'll find the speed by which we're generating articles to be much faster.

**Comment by smokeyblues** [comment]
That did the trick. I got output. Not quite as eloquent as yours but I got something! Thanks
